<?php

return [
    [
        'category' => 'Company Profile',
        'questions' => [
            [
                'name' => 'website',
                'type' => 'url',
                'question' => 'Enter the company website URL.',
            ],
            // [
            //     'name' => 'linkedin',
            //     'type' => 'url',
            //     'question' => 'Enter the company LinkedIn page.',
            // ],
            [
                'name' => 'industry',
                'type' => 'select',
                'question' => 'What industry does the company primarily operate in?',
                'answers' => [],
            ],
            [
                'name' => 'employee_count',
                'type' => 'select',
                'question' => 'What is the company\'s approximate employee count?',
                'answers' => [
                    '1_10' => '1 - 10',
                    '11_50' => '11 - 50',
                    '51_200' => '51 - 200',
                    '201_500' => '201 - 500',
                    '501_1000' => '501 - 1,000',
                    '1001_5000' => '1,001 - 5,000',
                    '5001_10000' => '5,001 - 10,000',
                    '10000_plus' => '10,001 +',
                    'unknown' => 'Unknown',
                ],
            ],
            [
                'name' => 'annual_revenue',
                'type' => 'select',
                'question' => "What is the company's approximate annual revenue?",
                'answers' => [
                    'under_500k' => 'Under $500,000',
                    '500k_1m' => '$500,000 - $1 million',
                    '1m_2p5m' => '$1 million - $2.5 million',
                    '2p5m_5m' => '$2.5 million - $5 million',
                    '5m_10m' => '$5 million - $10 million',
                    '10m_100m' => '$10 million - $100 million',
                    '100m_500m' => '$100 million - $500 million',
                    '500m_1b' => '$500 million - $1 billion',
                    'over_1b' => 'Over $1 billion',
                    'unknown' => 'Unknown',
                ],
            ],
            [
                'name' => 'location',
                'type' => 'text_group',
                'question' => 'Where is the company headquartered?',
                'answers' => [
                    'city' => 'City',
                    'state' => 'State',
                    'country' => 'Country',
                ],
            ],
            [
                'name' => 'relationship',
                'type' => 'select',
                'question' => 'What is the company\'s relationship with us?',
                'answers' => [],
            ],
            [
                'name' => 'description',
                'type' => 'textarea',
                'question' => 'Provide a brief description of the company.',
            ],
            # opportunities / products and services ??
        ],
    ],
    [
        'category' => 'Operational Context',
        'questions' => [
            [
                'name' => 'products',
                'type' => 'textarea',
                'question' => 'What are the company\'s main products or services?',
            ],
            [
                'name' => 'customers',
                'type' => 'checkbox',
                'question' => 'Who are the company\'s primary customers?',
                'answers' => [
                    'individuals' => 'Individuals',
                    'small_business' => 'Small businesses',
                    'mid_business' => 'Mid-size businesses',
                    'large_business' => 'Large enterprises',
                    'government_orgs' => 'Government organizations',
                    'healthcare_orgs' => 'Healthcare organizations',
                    'educational_inst' => 'Educational institutions',
                    'nonprofits' => 'Nonprofit organizations',
                    'internal' => 'Internal departments or employees',
                    'other' => 'Other',
                    'unknown' => 'Unknown',
                ],
            ],
            [
                'name' => 'revenue_generation',
                'type' => 'checkbox',
                'question' => 'How does the company primarily generate revenue?',
                'answers' => [
                    'sales' => 'Product sales',
                    'services' => 'Professional or managed services',
                    'distribution' => 'Wholesale, distribution, or resale',
                    'subscriptions' => 'Recurring fees or subscriptions',
                    'usage' => 'Usage-based fees',
                    'contracts' => 'Contracts or project-based work',
                    'memberships' => 'Memberships',
                    'advertising' => 'Advertising',
                    'grants' => 'Donations or grants',
                    'funding' => 'Government funding',
                    'licensing' => 'Licensing or royalties',
                    'leasing' => 'Leasing or rentals',
                    'commission' => 'Commission or brokerage fees',
                    'other' => 'Other',
                    'unknown' => 'Unknown',
                ],
            ],
            [
                'name' => 'operating_activities',
                'type' => 'checkbox',
                'question' => 'What are the company\'s major operating activities?',
                'max_selections' => 5,
                'answers' => [
                    'marketing' => 'Marketing and generating demand',
                    'finding_customers' => 'Finding and qualifying customers',
                    'sales' => 'Selling products or services',
                    'contracts' => 'Creating proposals, quotes, or contracts',
                    'development' => 'Designing or developing products and services',
                    'onboarding' => 'Onboarding customers',
                    'delivery' => 'Delivering projects or services',
                    'manufacturing' => 'Manufacturing or producing goods',
                    'orders' => 'Processing and fulfilling orders',
                    'inventory' => 'Managing inventory, distribution, or logistics',
                    'support' => 'Supporting customers',
                    'billing' => 'Billing, accounting, and collecting payments',
                    'purchasing' => 'Purchasing goods or services',
                    'hiring' => 'Hiring and managing employees',
                    'it' => 'Managing IT systems and cybersecurity',
                    'facilities' => 'Maintaining equipment and facilities',
                    'risk' => 'Managing risk, compliance, or legal requirements',
                    'reports' => 'Creating reports and analyzing performance',
                    'other' => 'Other',
                    'unknown' => 'Unknown',
                ],
            ],
            [
                'name' => 'change',
                'type' => 'checkbox',
                'question' => 'What business changes have recently taken effect or will soon take effect within the company?',
                'answers' => [
                    'growth' => 'Radid company growth',
                    'decline' => 'Declining or uncertain demand',
                    'new_products' => 'Introduction of new products or services',
                    'new_markets' => 'Expansion into new customer markets or locations',
                    'merger' => 'Merger, acquisition, or change in ownership',
                    'restructuring' => 'Organizational restructuring or leadership changes',
                    'regulation' => 'Increased regulatory or compliance requirements',
                    'cost_pressure' => 'Cost-reduction or financial pressure',
                    'hiring_issues' => 'Hiring difficulties or staffing shortages',
                    'experience' => 'Loss of experienced employees or institutional knowledge',
                    'logistics' => 'Challenges with supply-chain, vendors, or logistics',
                    'technology' => 'Adoption of modern technologies or system upgrades',
                    'security' => 'Increased security or privacy concerns',
                    'competition' => 'Increased competition',
                    'expectations' => 'Changing customer expectations or satisfaction',
                    'none' => 'No major changes',
                    'other' => 'Other',
                    'unknown' => 'Unknown',
                ]
            ]
        ],
    ],
    [
        'category' => 'Business Priorities',
        'questions' => [
            [
                'name' => 'outcomes',
                'type' => 'checkbox',
                'max_selections' => 3,
                'question' => 'What are the most important business outcomes for the company over the next 12 to 24 months?',
                'answers' => [
                    'revenue' => 'Increased revenue',
                    'margins' => 'Improved margins',
                    'acquisition' => 'Customer acquisition',
                    'retention' => 'Customer retention',
                    'expansion' => 'Market or geographic expansion',
                    'development' => 'Development of new products or services',
                    'experience' => 'Customer experience',
                    'efficiency' => 'Increased product or service delivery efficiency',
                    'quality' => 'Improved product or service quality',
                    'productivity' => 'Increased employee productivity',
                    'satisfaction' => 'Higher employee satisfaction',
                    'costs' => 'Reduction in operation costs',
                    'errors' => 'Errors, rework, or waste reduction',
                    'capacity' => 'Increased operational capacity',
                    'staffing' => 'Adequate staffing and skills',
                    'decisions' => 'Improved decision-making',
                    'reporting' => 'Better reporting or visibility',
                    'cash' => 'Improved cash flow and collections',
                    'compliance' => 'Strengthened risk management or compliance',
                    'security' => 'Increased cybersecurity, privacy, or resiliance',
                    'technology' => 'Technology or process modernization',
                    'other' => 'Other',
                    'unknown' => 'Unknown',
                ],
            ],
            [
                'name' => 'obstacles',
                'type' => 'checkbox',
                'max_selections' => 5,
                'question' => 'What are the most significant obstacles to achieving the company\'s goals?',
                'answers' => [
                    'staff' => 'Insufficient staff or limited employee capacity',
                    'skills' => 'Difficulty hiring or retaining skilled employees',
                    'repetition' => 'Excessive repetitive or manual work',
                    'inefficiency' => 'Slow or inefficient business processes',
                    'systems' => 'Disconnected systems or duplicate data entry',
                    'information' => 'Difficulty finding needed information',
                    'data' => 'Incomplete, inaccurate, or outdated data',
                    'visibility' => 'Limited reporting or visibility into performance',
                    'decisions' => 'Slow or inconsistent decision-making',
                    'change' => 'Organizational resistance to change',
                    'coordination' => 'Poor coordination between departments',
                    'dependence' => 'Overreliance on small set of experienced employees',
                    'experience' => 'Inconsistent customer or service experiences',
                    'demand' => 'Difficulty keeping up with demand',
                    'technology' => 'Inadequate or outdated technology',
                    'budget' => 'Budget or cost constraints',
                    'security' => 'Security, privacy, or compliance requirements',
                    'ownership' => 'Unclear ownership or accountability',
                    'other' => 'Other',
                    'unknown' => 'Unknown',
                ],
            ],
        ],
    ],
];
